package com.fotile.recipe.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        DAIngredientDao.createTable(db, ifNotExists);
        DBIngredientDao.createTable(db, ifNotExists);
        DCIngredientDao.createTable(db, ifNotExists);
        DCookingPromptsInfoDao.createTable(db, ifNotExists);
        DCookingStepDao.createTable(db, ifNotExists);
        DDeviceDao.createTable(db, ifNotExists);
        DDIngredientDao.createTable(db, ifNotExists);
        DMajorIngredientDao.createTable(db, ifNotExists);
        DMinorIngredientDao.createTable(db, ifNotExists);
        DProductsDao.createTable(db, ifNotExists);
        DPromptContentDao.createTable(db, ifNotExists);
        DPropertiesDao.createTable(db, ifNotExists);
        DReadyStepDao.createTable(db, ifNotExists);
        DRecipeDao.createTable(db, ifNotExists);
        DRecipeBannerDao.createTable(db, ifNotExists);
        DRecipeCategoryDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        DAIngredientDao.dropTable(db, ifExists);
        DBIngredientDao.dropTable(db, ifExists);
        DCIngredientDao.dropTable(db, ifExists);
        DCookingPromptsInfoDao.dropTable(db, ifExists);
        DCookingStepDao.dropTable(db, ifExists);
        DDeviceDao.dropTable(db, ifExists);
        DDIngredientDao.dropTable(db, ifExists);
        DMajorIngredientDao.dropTable(db, ifExists);
        DMinorIngredientDao.dropTable(db, ifExists);
        DProductsDao.dropTable(db, ifExists);
        DPromptContentDao.dropTable(db, ifExists);
        DPropertiesDao.dropTable(db, ifExists);
        DReadyStepDao.dropTable(db, ifExists);
        DRecipeDao.dropTable(db, ifExists);
        DRecipeBannerDao.dropTable(db, ifExists);
        DRecipeCategoryDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DAIngredientDao.class);
        registerDaoClass(DBIngredientDao.class);
        registerDaoClass(DCIngredientDao.class);
        registerDaoClass(DCookingPromptsInfoDao.class);
        registerDaoClass(DCookingStepDao.class);
        registerDaoClass(DDeviceDao.class);
        registerDaoClass(DDIngredientDao.class);
        registerDaoClass(DMajorIngredientDao.class);
        registerDaoClass(DMinorIngredientDao.class);
        registerDaoClass(DProductsDao.class);
        registerDaoClass(DPromptContentDao.class);
        registerDaoClass(DPropertiesDao.class);
        registerDaoClass(DReadyStepDao.class);
        registerDaoClass(DRecipeDao.class);
        registerDaoClass(DRecipeBannerDao.class);
        registerDaoClass(DRecipeCategoryDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
