package com.fotile.recipe.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.fotile.recipe.bean.recipe.DDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DDEVICE".
*/
public class DDeviceDao extends AbstractDao<DDevice, Long> {

    public static final String TABLENAME = "DDEVICE";

    /**
     * Properties of entity DDevice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property RecipeId = new Property(1, String.class, "recipeId", false, "RECIPE_ID");
        public final static Property Id = new Property(2, String.class, "id", false, "ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Time = new Property(4, String.class, "time", false, "TIME");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property DeviceId = new Property(6, String.class, "deviceId", false, "DEVICE_ID");
        public final static Property AutoType = new Property(7, String.class, "autoType", false, "AUTO_TYPE");
        public final static Property AutoValue = new Property(8, String.class, "autoValue", false, "AUTO_VALUE");
    }

    private DaoSession daoSession;

    private Query<DDevice> dRecipe_DevicesQuery;

    public DDeviceDao(DaoConfig config) {
        super(config);
    }
    
    public DDeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DDEVICE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"RECIPE_ID\" TEXT," + // 1: recipeId
                "\"ID\" TEXT," + // 2: id
                "\"NAME\" TEXT," + // 3: name
                "\"TIME\" TEXT," + // 4: time
                "\"TITLE\" TEXT," + // 5: title
                "\"DEVICE_ID\" TEXT," + // 6: deviceId
                "\"AUTO_TYPE\" TEXT," + // 7: autoType
                "\"AUTO_VALUE\" TEXT);"); // 8: autoValue
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DDEVICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DDevice entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String recipeId = entity.getRecipeId();
        if (recipeId != null) {
            stmt.bindString(2, recipeId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(7, deviceId);
        }
 
        String autoType = entity.getAutoType();
        if (autoType != null) {
            stmt.bindString(8, autoType);
        }
 
        String autoValue = entity.getAutoValue();
        if (autoValue != null) {
            stmt.bindString(9, autoValue);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DDevice entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String recipeId = entity.getRecipeId();
        if (recipeId != null) {
            stmt.bindString(2, recipeId);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
 
        String deviceId = entity.getDeviceId();
        if (deviceId != null) {
            stmt.bindString(7, deviceId);
        }
 
        String autoType = entity.getAutoType();
        if (autoType != null) {
            stmt.bindString(8, autoType);
        }
 
        String autoValue = entity.getAutoValue();
        if (autoValue != null) {
            stmt.bindString(9, autoValue);
        }
    }

    @Override
    protected final void attachEntity(DDevice entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DDevice readEntity(Cursor cursor, int offset) {
        DDevice entity = new DDevice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // recipeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // time
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // deviceId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // autoType
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // autoValue
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DDevice entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecipeId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDeviceId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAutoType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAutoValue(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DDevice entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DDevice entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DDevice entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "devices" to-many relationship of DRecipe. */
    public List<DDevice> _queryDRecipe_Devices(String recipeId) {
        synchronized (this) {
            if (dRecipe_DevicesQuery == null) {
                QueryBuilder<DDevice> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RecipeId.eq(null));
                dRecipe_DevicesQuery = queryBuilder.build();
            }
        }
        Query<DDevice> query = dRecipe_DevicesQuery.forCurrentThread();
        query.setParameter(0, recipeId);
        return query.list();
    }

}
